/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:dbd92b1f-e9b5-4ad7-8902-96107552239d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_w7qfPvpLp",
    "aws_user_pools_web_client_id": "pam4hkhmrldholjv8d4eckfgl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xoguq4zrijbyldosjlab6aq3xy.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
